service: serverless-example

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    RDS_HOSTNAME:
      Fn::GetAtt:
        - MyRDSInstance
        - Endpoint.Address
    RDS_PORT:
      Fn::GetAtt:
        - MyRDSInstance
        - Endpoint.Port
    RDS_USERNAME: postgres
    RDS_PASSWORD: postgres
    RDS_DB_NAME: postgres

resources:
  Resources:
    MyRDSInstance:
      Type: AWS::RDS::DBInstance
      Properties:
        Engine: postgres
        DBInstanceIdentifier: epam-db
        MasterUsername: postgres
        MasterUserPassword: postgres
        AllocatedStorage: 20
        DBInstanceClass: db.t2.micro
        VPCSecurityGroups:
          - sg-02dff6b4120cb3abd
        AvailabilityZone: us-east-1
        PubliclyAccessible: true

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'